workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: AppManagerKey
    environment:
      vars:
        APP_STORE_APPLE_ID: 6742403694
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: at.foodconnect
    scripts:
      - name: Cloud Firestore Fix
        script: |
          rm -rf ios 
          flutter create .
          rm -rf test

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}' 

      - name: Get Flutter packages
        script: |
          flutter pub get
          dart run flutter_launcher_icons

      - name: Install Pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter analyze
        script: |
          flutter analyze
        
      - name: Fix Bundle Identifier and Platform key
        script: |
          cat ios/Runner.xcodeproj/project.pbxproj | grep PRODUCT_BUNDLE_IDENTIFIER
          perl -pi -e 's/PRODUCT_BUNDLE_IDENTIFIER = at\.hfs\.foodconnect/PRODUCT_BUNDLE_IDENTIFIER = at.foodconnect/g' ios/Runner.xcodeproj/project.pbxproj
          cat ios/Runner.xcodeproj/project.pbxproj | grep PRODUCT_BUNDLE_IDENTIFIER
          perl -pi -e 's/# platform :ios, .*/platform :ios, "16.0"/' ios/Podfile
          cat ios/Podfile | grep platform

      - name: Update Versions in AppFramework
        script: |
          cat ios/Flutter/AppframeworkInfo.plist
          perl -pi -e 's/12\.0/16\.0/g' ios/Flutter/AppframeworkInfo.plist
          perl -pi -e 's/1\.0/2\.0/g' ios/Flutter/AppframeworkInfo.plist 
          cat ios/Flutter/AppframeworkInfo.plist
          perl -pi -e 's#(</dict>)#    <key>NSLocationWhenInUseUsageDescription</key>\n    <string>Diese App benötigt Zugriff auf deinen Standort, um Restaurants in deiner Nähe zu zeigen.</string>\n    <key>NSLocationAlwaysUsageDescription</key>\n    <string>Diese App benötigt Zugriff auf deinen Standort für eine verbesserte Kartenfunktionalität.</string>\n    <key>NSLocationWhenInUseUsageDescription</key>\n    <string>Wir verwenden deine Standortdaten nur, um Restaurants in deiner Umgebung anzuzeigen.</string>\n    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>\n    <string>Diese App benötigt den Standortzugriff, um dir Restaurants in deiner Umgebung zu zeigen.</string>\n\n$1#' ios/Runner/Info.plist
          perl -pi -e 's#(</dict>)#    <key>NSCameraUsageDescription</key>\n    <string>Diese App benötigt Zugriff auf die Kamera, um Profilbilder aufzunehmen.</string>\n    <key>NSPhotoLibraryUsageDescription</key>\n    <string>Diese App benötigt Zugriff auf die Galerie, um Profilbilder auszuwählen.</string>\n\n$1#' ios/Runner/Info.plist
          perl -pi -e 's#(</dict>)#    <key>GIDClientID</key>\n    <string>593098836626-c7522bskeudkakk0lq3e0ndp5bjd5slo.apps.googleusercontent.com</string>\n    <key>CFBundleURLTypes</key>\n    <array>\n    <dict>\n    <key>CFBundleTypeRole</key>\n    <string>Editor</string>\n    <key>CFBundleURLSchemes</key>\n    <array>\n    <string>com.googleusercontent.apps.593098836626-c7522bskeudkakk0lq3e0ndp5bjd5slo</string>\n    </array>\n    </dict>\n    </array>\n\n$1#' ios/Runner/Info.plist
          cat ios/Runner/Info.plist

      - name: Update App Delegate
        script: |
          cat ios/Runner/AppDelegate.swift
          perl -pi -e 's/(^\s*import UIKit\s*)/$1\nimport Firebase/' ios/Runner/AppDelegate.swift
          perl -pi -e 's/(^\s*import Firebase\s*)/$1\nimport flutter_local_notifications/' ios/Runner/AppDelegate.swift
          perl -pi -e 's/(^\s+)(GeneratedPluginRegistrant.register\(with: self\))/$1FirebaseApp.configure()\n$1$2/' ios/Runner/AppDelegate.swift
          perl -pi -e 's/^(\s*GeneratedPluginRegistrant\.register\(with: self\))/\n    FlutterLocalNotificationsPlugin.setPluginRegistrantCallback { (registry) in\n      GeneratedPluginRegistrant.register(with: registry)\n    }\n\n$1/s' ios/Runner/AppDelegate.swift
          perl -pi -e 's/^(.*GeneratedPluginRegistrant\.register\(with: self\).*)$/$1\n\n    if #available(iOS 10.0, *) {\n      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate\n    }\n/s' ios/Runner/AppDelegate.swift
          cat ios/Runner/AppDelegate.swift

      - name: Flutter build ipa
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
          flutter build ipa --release \
            --build-name=1.0.6 \
            --build-number=4 \
            --export-options-plist=/Users/builder/export_options.plist

      - name: Check IPA for App Icons
        script: |
          unzip -l build/ios/ipa/foodconnect.ipa | grep "AppIcon"

      
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: false
        beta_groups:
          - Test1
          - InteralTesting
          - Tester
        submit_to_app_store: false