workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: AppManagerKey
    environment:
      vars:
        APP_STORE_APPLE_ID: 6742403694
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: at.foodconnect
    scripts:
      - name: Cloud Firestore Fix
        script: |
          rm -rf ios
          flutter create .
          rm -rf test
      
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles \
          --custom-export-options='{"testFlightInternalTestingOnly": true}'

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install Pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter analyze
        script: |
          flutter analyze
        
      - name: Fix Bundle Identifier and Platform key
        script: |
          cat ios/Runner.xcodeproj/project.pbxproj | grep PRODUCT_BUNDLE_IDENTIFIER
          perl -pi -e 's/PRODUCT_BUNDLE_IDENTIFIER = at\.hfs\.foodconnect/PRODUCT_BUNDLE_IDENTIFIER = at.foodconnect/g' ios/Runner.xcodeproj/project.pbxproj
          cat ios/Runner.xcodeproj/project.pbxproj | grep PRODUCT_BUNDLE_IDENTIFIER
          perl -pi -e 's/platform :ios, .*/platform :ios, "16.0"/' ios/Podfile
          cat ios/Podfile | grep platform

      - name: Flutter build ipa
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: false
        beta_groups:
          - Test1
        submit_to_app_store: false