workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: AppManagerKey
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: at.foodconnect
      vars:
        APP_ID: 6742403694 # <-- Put your APP ID here
      flutter: stable
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Fetch Flutter Dependencies
        script: |
          flutter pub get
      - name: Clean Xcode project
        script: |
          cd ios
          xcodebuild clean -workspace Runner.xcworkspace -scheme Runner
      - name: Update Pod Repo
        script: |
          cd ios
          pod repo update
      - name: Deintegrate Pods
        script: |
          cd ios
          pod deintegrate
      - name: Delete Pods and Podfile.lock
        script: |
          cd ios
          rm -rf Pods Podfile.lock
      - name: Reinstall pods and Xcode Settings
        script: |
          cd ios
          pod deintegrate
          pod install --repo-update
          xcodebuild -workspace Runner.xcworkspace -scheme Runner clean
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Clean iOS Build Files
        script: |
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.podspec
          rm -rf ios/Runner.xcworkspace
          rm -rf ios/Runner.xcodeproj/project.xcworkspace
      - name: Xcode Derived Data Cleanup
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Flutter build ipa and automatic versioning
        script: |
          # See the following link about getting the latest App Store or TestFlight version - https://docs.codemagic.io/knowledge-codemagic/build-versioning/#app-store-or-testflight-latest-build-number
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
          auth: integration
          
          # Configuration related to TestFlight (optional)
          # Note: This action is performed during post-processing.
          submit_to_testflight: true
          beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
            - Test1

          # Configuration related to App Store (optional)
          # Note: This action is performed during post-processing.
          submit_to_app_store: false  