workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: AppManagerKey
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: at.foodconnect
      vars:
        APP_ID: 6742403694 # <-- Deine App ID
      flutter: stable
      xcode: latest # Falls nötig, auf eine feste Version setzen, z.B. "15.0"
      cocoapods: default

    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Clean iOS Build Files
        script: |
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.podspec
          rm -rf ios/Runner.xcworkspace
          rm -rf ios/Runner.xcodeproj/project.xcworkspace
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Fetch Flutter Dependencies
        script: |
          flutter clean
          flutter pub get
          flutter pub cache repair
          flutter gen-l10n || echo "No localization setup, skipping..."
          flutter pub run build_runner build --delete-conflicting-outputs


      - name: Ensure Runner.xcworkspace Exists
        script: |
          cd ios
          if [ ! -d "Runner.xcworkspace" ]; then
            echo "Runner.xcworkspace fehlt! Versuche ihn mit Xcode zu erstellen..."
            xcodebuild -list || true
          else
            echo "Runner.xcworkspace existiert bereits."
          fi
          ls -la

      - name: Ensure Podfile Changes are Applied
        script: |
          cd ios
          rm -rf Podfile.lock
          pod install --repo-update --clean-install

      - name: Flutter analyze
        script: |
          flutter analyze

      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true

      - name: Flutter build ipa and automatic versioning
        script: |
          if [ ! -f "ios/Runner/GeneratedPluginRegistrant.m" ]; then
            echo "❌ Fehler: GeneratedPluginRegistrant.m nicht gefunden! Versuche es zu regenerieren..."
            flutter pub run build_runner build --delete-conflicting-outputs
            flutter pub get
          fi

          cd ios
          if [ ! -d "Pods" ]; then
            echo "❌ Pods fehlen! Starte pod install..."
            pod install --repo-update
          fi
          cd ..

          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1))

          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
          auth: integration
          
          # Configuration related to TestFlight (optional)
          # Note: This action is performed during post-processing.
          submit_to_testflight: true
          beta_groups: 
            - Test1

          # Configuration related to App Store (optional)
          # Note: This action is performed during post-processing.
          submit_to_app_store: false  