workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: AppManagerKey
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: at.foodconnect
      vars:
        APP_ID: 6742403694 # <-- Deine App ID
      flutter: stable
      xcode: latest # Falls nötig, auf eine feste Version setzen, z.B. "15.0"
      cocoapods: default

    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Clean iOS Build Files
        script: |
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.podspec
          rm -rf ios/Runner.xcworkspace
          rm -rf ios/Runner.xcodeproj/project.xcworkspace
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Fetch Flutter Dependencies
        script: |
          flutter clean
          flutter pub get
          flutter pub cache repair
          flutter gen-l10n || echo "No localization setup, skipping..."
          flutter pub run build_runner build --delete-conflicting-outputs


      - name: Ensure Runner.xcworkspace Exists
        script: |
          cd ios
          if [ ! -d "Runner.xcworkspace" ]; then
            echo "Runner.xcworkspace fehlt! Erstelle es neu..."
            pod install --repo-update
          fi
          ls -la
          pod deintegrate
          pod install --repo-update --clean-install
          cd ..

      - name: Ensure Podfile Changes are Applied
        script: |
          cd ios
          rm -rf Podfile.lock
          pod install --repo-update --clean-install

      - name: Fix Podfile Configuration
        script: |
          cd ios
          echo "🔧 Fixing Xcode config..."
          # Stelle sicher, dass die richtigen xcconfig-Dateien verwendet werden
          sed -i '' 's|Pods-Runner.release.xcconfig|Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig|' Runner.xcodeproj/project.pbxproj
          sed -i '' 's|Pods-Runner.profile.xcconfig|Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig|' Runner.xcodeproj/project.pbxproj

      - name: Flutter analyze
        script: |
          flutter analyze

      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true

      - name: Flutter build ipa and automatic versioning
        script: |
          # Stelle sicher, dass `GeneratedPluginRegistrant.m` existiert
          if [ ! -f "ios/Runner/GeneratedPluginRegistrant.m" ]; then
            echo "❌ Fehler: GeneratedPluginRegistrant.m nicht gefunden! Versuche es zu regenerieren..."
            flutter pub run build_runner build --delete-conflicting-outputs
            flutter pub get
          fi

          # Stelle sicher, dass Pods richtig installiert sind
          cd ios
          if [ ! -d "Pods" ]; then
            echo "❌ Pods fehlen! Starte pod install..."
            pod install --repo-update
          fi
          cd ..

          echo "🔧 Fixing Xcode module maps..."
          rm -rf ios/Flutter/Flutter.podspec
          rm -rf ios/.symlinks
          rm -rf ios/Pods
          rm -rf ios/Runner.xcworkspace
          rm -rf ~/Library/Developer/Xcode/DerivedData
          flutter clean
          flutter pub get
          cd ios && pod install --repo-update && cd ..

          # Baue die iOS-App mit Flutter
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
          auth: integration
          
          # Configuration related to TestFlight (optional)
          # Note: This action is performed during post-processing.
          submit_to_testflight: true
          beta_groups: 
            - Test1

          # Configuration related to App Store (optional)
          # Note: This action is performed during post-processing.
          submit_to_app_store: false  