workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: AppManagerKey
    environment:
      vars:
        APP_STORE_APPLE_ID: 6742403694
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: at.foodconnect
    scripts:
      - name: Cloud Firestore Fix
        script: |
          rm -rf ios 
          flutter create .
          rm -rf test

      - name: Restore App Icon from ZIP
        script: |
          ls -la ios/Runner/Assets.xcassets/AppIcon.appiconset
          rm -rf ios/Runner/Assets.xcassets/AppIcon.appiconset
          mkdir -p ios/Runner/Assets.xcassets/AppIcon.appiconset
          unzip assets/app_icons.zip -d ios/Runner/Assets.xcassets/AppIcon.appiconset
          ls -la ios/Runner/Assets.xcassets/AppIcon.appiconset
          cat ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json

      - name: Check if Xcode detects App Icon
        script: |
          xcrun actool ios/Runner/Assets.xcassets --compile /tmp/Assets --platform iphoneos --minimum-deployment-target 16.0 --app-icon AppIcon --output-format human-readable-text
      
      - name: Ensure Xcode includes Assets.xcassets
        script: |
          plutil -replace CFBundleIcons -json '{
            "CFBundlePrimaryIcon": {
              "CFBundleIconFiles": ["AppIcon"],
              "CFBundleIconName": "AppIcon"
            }
          }' ios/Runner/Info.plist
          cat ios/Runner/Info.plist

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles \
          --custom-export-options='{"testFlightInternalTestingOnly": true}'

      - name: Get Flutter packages
        script: |
          flutter pub get


      - name: Install Pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter analyze
        script: |
          flutter analyze
        
      - name: Fix Bundle Identifier and Platform key
        script: |
          cat ios/Runner.xcodeproj/project.pbxproj | grep PRODUCT_BUNDLE_IDENTIFIER
          perl -pi -e 's/PRODUCT_BUNDLE_IDENTIFIER = at\.hfs\.foodconnect/PRODUCT_BUNDLE_IDENTIFIER = at.foodconnect/g' ios/Runner.xcodeproj/project.pbxproj
          cat ios/Runner.xcodeproj/project.pbxproj | grep PRODUCT_BUNDLE_IDENTIFIER
          perl -pi -e 's/# platform :ios, .*/platform :ios, "16.0"/' ios/Podfile
          cat ios/Podfile | grep platform

      - name: Update Versions in AppFramework
        script: |
          cat ios/Flutter/AppframeworkInfo.plist
          perl -pi -e 's/12\.0/16\.0/g' ios/Flutter/AppframeworkInfo.plist
          perl -pi -e 's/1\.0/2\.0/g' ios/Flutter/AppframeworkInfo.plist 
          cat ios/Flutter/AppframeworkInfo.plist
          perl -pi -e 's#(</dict>)#    <key>NSLocationWhenInUseUsageDescription</key>\n    <string>Diese App benötigt Zugriff auf deinen Standort, um Restaurants in deiner Nähe zu zeigen.</string>\n    <key>NSLocationAlwaysUsageDescription</key>\n    <string>Diese App benötigt Zugriff auf deinen Standort für eine verbesserte Kartenfunktionalität.</string>\n    <key>NSLocationWhenInUseUsageDescription</key>\n    <string>Wir verwenden deine Standortdaten nur, um Restaurants in deiner Umgebung anzuzeigen.</string>\n    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>\n    <string>Diese App benötigt den Standortzugriff, um dir Restaurants in deiner Umgebung zu zeigen.</string>\n\n$1#' ios/Runner/Info.plist
          cat ios/Runner/Info.plist

      - name: Verify AppIcon before build
        script: |
          find ios/Runner/Assets.xcassets -name "*.png"

      - name: Force Xcode to compile assets
        script: |
          xcrun actool ios/Runner/Assets.xcassets \
            --compile /tmp/Assets \
            --platform iphoneos \ 
            --minimum-deployment-target 16.0 \
            --app-icon AppIcon \
            --output-partial-info-plist /tmp/Info.plist

      - name: Flutter build ipa
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
          flutter build ipa --release \
            --build-name=1.0.2 \
            --build-number=6 \
            --export-options-plist=/Users/builder/export_options.plist

      - name: Check IPA for App Icons
        script: |
          unzip -l build/ios/ipa/foodconnect.ipa | grep "AppIcon"

      
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: false
        beta_groups:
          - Test1
        submit_to_app_store: false