workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: AppManagerKey
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: at.foodconnect
      vars:
        APP_ID: 6742403694 # <-- Deine App ID
      flutter: stable
      xcode: latest # Falls nötig, auf eine feste Version setzen, z.B. "15.0"
      cocoapods: default

    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Clean Xcode project
        script: |
          cd ios
          xcodebuild clean -workspace Runner.xcworkspace -scheme Runner

      - name: Clean iOS Build Files
        script: |
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.podspec
          rm -rf ios/Runner.xcworkspace
          rm -rf ios/Runner.xcodeproj/project.xcworkspace
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Update Pod Repo
        script: |
          cd ios
          pod repo update

      - name: Deintegrate Pods
        script: |
          cd ios
          pod deintegrate

      - name: Delete Pods and Podfile.lock
        script: |
          cd ios
          rm -rf Pods Podfile.lock

      - name: Clean Derived Data & Xcode Cache
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ~/.pub-cache
          flutter clean
          flutter pub get

      - name: Delete Podfile.lock and Reset CocoaPods
        script: |
          cd ios
          rm -rf Podfile.lock
          rm -rf ~/Library/Caches/CocoaPods
          pod cache clean --all

      - name: Reinstall Pods and Xcode Settings
        script: |
          cd ios
          pod deintegrate
          rm -rf Pods Podfile.lock
          pod install --repo-update --clean-install || {
            echo "Pod install fehlgeschlagen! Versuche es erneut..."
            pod install --repo-update
          }

          if [ ! -d "Runner.xcworkspace" ]; then
            echo "Runner.xcworkspace fehlt! Erstelle es neu..."
            pod install --repo-update
          fi

          ls -la


      - name: Ensure Runner.xcworkspace Exists
        script: |
          cd ios
          if [ ! -f "Runner.xcworkspace" ]; then
            echo "Runner.xcworkspace fehlt! Erstelle es neu..."
            pod install
          else
            echo "Runner.xcworkspace existiert bereits."
          fi

      - name: Ensure Podfile Changes are Applied
        script: |
          cd ios
          rm -rf Podfile.lock
          pod install --repo-update --clean-install

      - name: Fetch Flutter Dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Flutter analyze
        script: |
          flutter analyze

      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true

      - name: Full Cleanup Before Xcode Build
        script: |
          cd ios
          rm -rf Pods
          rm -rf .symlinks
          rm -rf Flutter/Flutter.podspec
          rm -rf Runner.xcworkspace
          rm -rf Runner.xcodeproj/project.xcworkspace
          pod deintegrate
          pod install --repo-update
          flutter clean
          flutter pub get

      - name: Flutter build ipa and automatic versioning
        script: |
          # Siehe: https://docs.codemagic.io/knowledge-codemagic/build-versioning/#app-store-or-testflight-latest-build-number
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
          auth: integration
          
          # Configuration related to TestFlight (optional)
          # Note: This action is performed during post-processing.
          submit_to_testflight: true
          beta_groups: 
            - Test1

          # Configuration related to App Store (optional)
          # Note: This action is performed during post-processing.
          submit_to_app_store: false  