// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8CNadwfAeKvbYrPuPVzQ9TN8Df9fzlYA',
    appId: '1:593098836626:web:4d377fb1d6f9504e07b44b',
    messagingSenderId: '593098836626',
    projectId: 'food-connect-hfs',
    authDomain: 'food-connect-hfs.firebaseapp.com',
    storageBucket: 'food-connect-hfs.appspot.com',
    measurementId: 'G-FPNCGSH0WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAaJ2Bleg5S2Rk5YVx-41HHCgBpewo01g',
    appId: '1:593098836626:android:66d688f97cf695fe07b44b',
    messagingSenderId: '593098836626',
    projectId: 'food-connect-hfs',
    storageBucket: 'food-connect-hfs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0np0BiZPQoU05j8kUt8Kn5zhIZj-5ds0',
    appId: '1:593098836626:ios:9a18af84a28e31f607b44b',
    messagingSenderId: '593098836626',
    projectId: 'food-connect-hfs',
    storageBucket: 'food-connect-hfs.appspot.com',
    iosBundleId: 'at.foodconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8CNadwfAeKvbYrPuPVzQ9TN8Df9fzlYA',
    appId: '1:593098836626:web:25c7c1a4809e012907b44b',
    messagingSenderId: '593098836626',
    projectId: 'food-connect-hfs',
    authDomain: 'food-connect-hfs.firebaseapp.com',
    storageBucket: 'food-connect-hfs.appspot.com',
    measurementId: 'G-XSRN3ZL7C4',
  );

}