# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Pods for Runner
  pod 'Firebase/Firestore'

  pod 'Flutter', :path => 'Flutter'

  install! 'cocoapods', :disable_input_output_paths => true

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
